In [165]:
import math
import copy
import numpy as np
import matplotlib.pyplot as plt 

x_train = np.array([1,3,4,5,6])
y_train = np.array([10,20,30,40,50])
w=1
b=1

In [166]:
def prediction(x,y,w,b):
    return w*x+b

In [167]:
def cost(actual,predicted):
    return (1/2)*np.mean(actual-predicted)**2

In [168]:
def gradient_descent(x, y, w, b):
    alpha = 0.01  # Learning rate
    iters = 10  # Number of iterations
    dw_db = []  # To store history of w and b
    cost_history = []  # To store history of cost

    for i in range(iters):
        # Step 1: Make predictions
        pred = prediction(x ,y, w, b)
        print(pred)
        # Step 2: Compute cost
        error = pred - y
        print(error)
        current_cost = cost(y, pred)

        # Step 3: Compute gradients
        dw = (1 / len(y)) * np.dot(x, error)
        print(dw)
        db = (1 / len(y)) * np.sum(error)    # Gradient w.r.t. b
      
        # Step 4: Update parameters
        w = w - alpha * dw
        b = b - alpha * db

        # Store history
        dw_db.append([w, b])
        cost_history.append(current_cost)

    return dw_db, cost_history
w_b,cost=gradient_descent(x_train,y_train,w,b)

[2 4 5 6 7]
[ -8 -16 -25 -34 -43]
-116.80000000000001
[ 3.42   7.756  9.924 12.092 14.26 ]
[ -6.58  -12.244 -20.076 -27.908 -35.74 ]
-95.51920000000001
[ 4.580288 10.826672 13.949864 17.073056 20.196248]
[ -5.419712  -9.173328 -16.050136 -22.926944 -29.803752]
-78.1194944
[ 5.52823069 13.33700458 17.24139152 21.14577846 25.05016541]
[ -4.47176931  -6.66299542 -12.75860848 -18.85422154 -24.94983459]
-63.893060947200006
[ 6.30255616 15.38919126 19.93250882 24.47582637 29.01914392]
[ -3.69744384  -4.61080874 -10.06749118 -15.52417363 -20.98085608]
-52.261167879372785
[ 6.93492938 17.06678785 22.13271708 27.19864631 32.26457554]
[ -3.06507062  -2.93321215  -7.86728292 -12.80135369 -17.73542446]
-42.75063078998542
[ 7.45124038 18.43811146 23.931547   29.42498254 34.91841808]
[ -2.54875962  -1.56188854  -6.068453   -10.57501746 -15.08158192]
-34.97456321935304
[ 7.87265741 19.55901976 25.40220093 31.2453821  37.08856327]
[ -2.12734259  -0.44098024  -4.59779907  -8.7546179  -12.91143673]
-28.

In [169]:
print(w_b)
print()
print(cost)

[[2.168, 1.252], [3.1231920000000004, 1.457096], [3.9043869440000005, 1.623843744], [4.543317553472001, 1.759238602688], [5.065929232265729, 1.869000149629184], [5.493435540165583, 1.9578048373067944], [5.843181172359113, 2.0294762384074345], [6.129347551309145, 2.087140591473714], [6.363529734905352, 2.1333539786092293], [6.555208109844671, 2.1702063088967334]]

[317.52, 210.32184607999997, 139.02405064544763, 91.65883879571744, 60.237985934608645, 39.4313627675897, 25.68394867864402, 16.62588807276261, 10.678385752685083, 6.79047123809654]


In [ ]:
##  practice  try on another data set 
import numpy as np 

x_train =np.array([3,5,7,9,11,13])
y_train = np.array([9,25,81,222 ,313,444])


def model_pre(x,y,w,b):
    return w*x +b


In [43]:
def compute_cost (x,y):
    error = (x - y)**2
    ave_cost = 1/(2*len(x))*np.sum(error)
    return (ave_cost)

In [44]:
def gradient_descent (x,y):
    alpha =0.01
    w =1
    b =1
    dw_db =[]
    cost_history = []
    iters = 10
    for i in range (iters):

      mo_pre = model_pre(x,y,w,b)
      print(f"pre_of_mod_for_G.D ={mo_pre} ")

      error = mo_pre - y
      curent_cost = compute_cost(mo_pre,y)     # here i call this function for cost history 
    
      dw = (1/len(y))*np.dot(error,x)
      print(f"derivative of w = {dw}")     # taking derivative / cost change of cost function  
      db = (1/len(y))*np.sum(error)

      w =w - alpha*dw    # updating w and b after cost change by derivative 
      b =b - alpha*db

      dw_db.append([w,b])
      cost_history.append(curent_cost)
    return dw_db , cost_history

dw_db,cost_his = gradient_descent(x_train ,y_train )


pre_of_mod_for_G.D =[ 4  6  8 10 12 14] 
derivative of w = -1905.0
pre_of_mod_for_G.D =[ 62.88333333 102.98333333 143.08333333 183.18333333 223.28333333
 263.38333333] 
derivative of w = -449.6833333333332
pre_of_mod_for_G.D =[ 76.56583333 125.6595     174.75316667 223.84683333 272.9405
 322.03416667] 
derivative of w = -107.88694444444445
pre_of_mod_for_G.D =[ 79.632775   130.88418056 182.13558611 233.38699167 284.63839722
 335.88980278] 
derivative of w = -27.609823148148315
pre_of_mod_for_G.D =[ 80.20679014 132.01039216 183.81399418 235.61759619 287.42119821
 339.22480023] 
derivative of w = -8.752626743827136
pre_of_mod_for_G.D =[ 80.19554432 132.17419888 184.15285343 236.13150798 288.11016254
 340.08881709] 
derivative of w = -4.320402789146138
pre_of_mod_for_G.D =[ 80.04706793 132.11213054 184.17719315 236.24225576 288.30731837
 340.37238098] 
derivative of w = -3.2760058018527234
pre_of_mod_for_G.D =[ 79.8665842  131.99716692 184.12774965 236.25833237 288.3889151
 340.51949782] 

In [45]:
print(f"updated w and b is ={dw_db}")
print()
print(f"cost_his = {cost_his}" )

updated w and b is =[[20.05, 2.7333333333333334], [24.546833333333332, 2.925333333333333], [25.625702777777775, 2.7556666666666665], [25.90180100925926, 2.5013871111111112], [25.98932727669753, 2.2275624925925928], [26.032531304588993, 1.9494740188641977], [26.06529136260752, 1.6707101076417696], [26.095564089623156, 1.3921130308900835], [26.125218219337096, 1.1138801067446635], [26.15469269149912, 0.8360571814635827]]

cost_his = [27180.0, 4584.779027777776, 3330.9143223842584, 3254.2261840774213, 3242.492075290138, 3234.363588953577, 3226.4567797381083, 3218.584925404846, 3210.7376574112322, 3202.9143348010357]


In [11]:
             # multi linear regression 

import numpy as np 

x_train =np.array ([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b_init = 785.1811367994083


In [12]:
def f_predict(x,w,b):
     return np.dot(x,w)+b

In [13]:
def cost_error(pred,y):
    
    extract_error_for_cost  = (pred - y)**2

    error = 1/(2*len(y))*np.sum(extract_error_for_cost )
    return error

In [16]:
def gradient(x,y,w,b):
    cost_history =[]
    dw_db = []
    alpha = 0.0001
    ini_w =np.zeros_like(w)
    ini_b =0
    iters =10

    for i in range(iters):
        pred_for_GD = f_predict(x,w,b)
        dw = 1/(len(y))*np.dot(x.T,pred_for_GD,x)
        db = 1/(len(y))*np.sum(pred_for_GD-y)

        w = w - alpha *dw
        b = b - alpha *db


        cost_history.append(cost_error(pred_for_GD,y))
        dw_db.append([f"dw = {[w]},db = {[b]}"])
    return dw_db, cost_history

dw_db,cost_history = gradient(x_train ,y_train ,w_init,b_init ) 
print(dw_db)
print()
print(cost_history)

        
        

[['dw = [array([  0.39133562,  18.75376741, -53.36032453, -26.42131617])],db = [785.1811367995756]'], ['dw = [array([  0.39127081,  18.75376726, -53.36032458, -26.42131781])],db = [785.1811367599847]'], ['dw = [array([  0.4066805 ,  18.75380272, -53.36031212, -26.42092783])],db = [785.181146172801]'], ['dw = [array([ -3.25692508,  18.74537179, -53.3632748 , -26.5136452 ])],db = [785.1789083055722]'], ['dw = [array([867.75375918,  20.74979986, -52.65890681,  -4.47038142])],db = [785.7109541895351]'], ['dw = [array([-206212.29249843,    -455.79665845,    -220.12017797,\n         -5245.18690291])],db = [659.2187213694251]'], ['dw = [array([4.90264163e+07, 1.12841623e+05, 3.95932695e+04, 1.24071866e+06])],db = [30732.348588789777]'], ['dw = [array([-1.16558759e+10, -2.68232629e+07, -9.42591470e+06, -2.94983260e+08])],db = [-7119059.538703613]'], ['dw = [array([2.77114779e+12, 6.37715073e+09, 2.24096879e+09, 7.01313345e+10])],db = [1692721437.8407354]'], ['dw = [array([-6.58831656e+14, -1.5

In [22]:
# try on another dat set 


import numpy as np

# Initialize training data
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

# Initialize weights and bias
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b_init = 785.1811367994083



# Prediction function
def f_predict(x, w, b):
    return np.dot(x, w) + b

# Cost function
def cost_error(pred, y):
    error = 1/(2*len(y))*np.sum((pred - y)**2)
    return error

# Gradient descent function
def gradient_descent(x, y, w, b, alpha, iterations):
    cost_history = []
    params_history = []

    for i in range(iterations):
        # Compute predictions
        pred = f_predict(x, w, b)
        
        # Compute gradients
        dw =  1/len(y)*np.dot(x.T, (pred - y))
        db = 1/len(y)*np.sum(pred - y) 

        # Update weights and bias
        w = w - alpha * dw
        b = b - alpha * db

        # Store cost and parameters
        cost_history.append(cost_error(pred, y))
        params_history.append({"w": w.copy(), "b": b})

    return params_history, cost_history

# Run gradient descent
alpha = 0.01  # Learning rate
iterations = 10 # Number of iterations
params_history, cost_history = gradient_descent(x_train, y_train, w_init, b_init, alpha, iterations)

# Print results
print("Final weights and bias:")
print(f"Weights: {params_history[-1]['w']}")
print(f"Bias: {params_history[-1]['b']}\n")
print("Cost history:")
print(cost_history)


Final weights and bias:
Weights: [-6.86785846e+34 -1.58047754e+32 -5.55389247e+31 -1.73809597e+33]
Bias: -4.195144667742205e+31

Cost history:
[1.5578904045996674e-12, 0.0008877299667991055, 505964.2105432726, 288375735781161.6, 1.643605679105914e+23, 9.367777150430035e+31, 5.339191136639052e+40, 3.043087120433513e+49, 1.734416128877831e+58, 9.88535388261581e+66]
